import img1 from "../photos/image1.jpeg";
import img2 from "../photos/image2.png";
import img3 from "../photos/image3.png";
import img4 from "../photos/image4.png";
import img5 from "../photos/image5.png";
import img6 from "../photos/image6.png";
import img7 from "../photos/image7.png";
// import img8 from "../photos/image8.png";
import img9 from "../photos/image9.png";
import img10 from "../photos/image10.png";
import img11 from "../photos/image11.png";
import img12 from "../photos/image12.png";
import img13 from "../photos/image13.png";
import img14 from "../photos/image14.png";
import img15 from "../photos/image15.png";
import img16 from "../photos/image16.png";
import img17 from "../photos/image17.png";
import img18 from "../photos/image18.png";
import img19 from "../photos/image19.png";
import img20 from "../photos/image20.png";
import img21 from "../photos/image21.png";
import img22 from "../photos/image22.png";
import img23 from "../photos/image23.png";
import img24 from "../photos/image24.png";
import img25 from "../photos/image25.png";
import img26 from "../photos/image26.png";
import img27 from "../photos/image27.png";
import img28 from "../photos/image28.png";
import img29 from "../photos/image29.png";
import img30 from "../photos/image30.png";
import img31 from "../photos/image31.png";
import img32 from "../photos/image32.png";
import img33 from "../photos/image33.png";
import img34 from "../photos/image34.png";
import img35 from "../photos/image35.png";
import img36 from "../photos/image36.png";
import img37 from "../photos/image37.png";
import img38 from "../photos/image38.png";
import img39 from "../photos/image39.png";
import img40 from "../photos/image40.png";
import img41 from "../photos/image41.png";
import img42 from "../photos/image42.png";
import img43 from "../photos/image43.png";
import img44 from "../photos/image44.png";
import img45 from "../photos/image45.png";
import img46 from "../photos/image46.png";
import img47 from "../photos/image47.png";
import img48 from "../photos/image48.png";

export const Coursesdata = [
  {
    id: 1,
    title: "700+ GB Ultimate Graphic Designing Pack",
    description: "All-in-one graphic designing resources and tools.",
    price: "₹249.00",
    originalPrice: "₹499.00",
    discount: "-94%",
    person: "photo",
    image: img1,
  },
  {
    id: 2,
    title: "Cohort 2 & 3 Both",
    description: "Combined courses for Cohort 2 and 3.",
    price: "₹549.00",
    originalPrice: "₹6,999.00",
    discount: "-98%",
    person: "Harkirat",
    image: img2,
  },
  {
    id: 3,
    title: "Dhruv Rathee All 3 Courses",
    description: "Access all three courses by Dhruv Rathee.",
    price: "₹399.00",
    originalPrice: "₹15,000.00",
    discount: "-97%",
    person: "Dhruv Rathee",
    image: img3,
  },
  {
    id: 4,
    title: "GDL (Gaurav Sen) InterviewReady – System Design Simplified 2023-10",
    description: "Master system design concepts for interviews.",
    price: "₹299.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Gaurav Sen",
    image: img4,
  },
  {
    id: 5,
    title: "GDL [AlgoZenith] Applied Algo & DS for Coding Competitions",
    description: "Learn algorithms and data structures for competitive coding.",
    price: "₹299.00",
    originalPrice: "₹6,969.00",
    discount: "-96%",
    person: "AlgoZenith",
    image: img5,
  },
  {
    id: 6,
    title: "GDL AevyTV Video Editing Cohort",
    description: "Learn video editing techniques and software.",
    price: "₹399.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "AevyTV",
    image: img6,
  },
  {
    id: 7,
    title: "GDL Alpha 5.0",
    description: "Join the Alpha 5.0 cohort for advanced learning.",
    price: "₹249.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Apna College",
    image: img7,
  },
  {
    id: 8,
    title: "GDL Alpha Batch",
    description: "Enroll in the Alpha Batch for intensive training.",
    price: "₹249.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Apna College",
    image: img7,
  },
  {
    id: 9,
    title: "GDL Alpha Plus – Plus Library",
    description: "Access the Plus Library for additional resources.",
    price: "₹249.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Apna College",
    image: img9,
  },
  {
    id: 10,
    title: "GDL Apna College – Alpha Plus +",
    description: "Join the Alpha Plus + program for enhanced learning.",
    price: "₹249.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Apna College",
    image: img10,
  },
  {
    id: 11,
    title: "GDL Apna College C++ DSA",
    description: "Learn C++ and data structures for programming.",
    price: "₹299.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Apna College",
    image: img11,
  },
  {
    id: 12,
    title: "GDL Arpit Bhaiya – System Design Beginner and Advanced",
    description: "Comprehensive system design course for all levels.",
    price: "₹299.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Arpit Bhayani",
    image: img12,
  },
  {
    id: 13,
    title: "GDL Arpit Bhayani – The System Design Masterclass",
    description: "Master system design with Arpit Bhayani.",
    price: "₹299.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Arpit Bhayani",
    image: img13,
  },
  {
    id: 14,
    title: "GDL Beerbiceps Instagram 101",
    description: "Learn the essentials of Instagram marketing.",
    price: "₹299.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Beerbiceps",
    image: img14,
  },
  {
    id: 15,
    title: "GDL Beerbiceps Monetising Content Creation",
    description: "Strategies to monetize your content effectively.",
    price: "₹299.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Beerbiceps",
    image: img15,
  },
  {
    id: 16,
    title: "GDL Beerbiceps Video Editing",
    description: "Learn video editing skills from Beerbiceps.",
    price: "₹399.00",
    originalPrice: "₹6,969.00",
    discount: "-96%",
    person: "Beerbiceps",
    image: img16,
  },
  {
    id: 17,
    title: "GDL Cohort 1 and 2 (0-100)",
    description: "Comprehensive course covering basics to advanced topics.",
    price: "₹299.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Harkirat",
    image: img17,
  },
  {
    id: 18,
    title: "GDL Delta 1.0",
    description: "Introduction to Delta program for skill enhancement.",
    price: "₹249.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Apna College",
    image: img18,
  },
  {
    id: 19,
    title: "GDL Delta 3.0",
    description: "Advanced Delta program for deeper learning.",
    price: "₹299.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Apna College",
    image: img19,
  },
  {
    id: 20,
    title: "GDL Delta 4",
    description: "Further your skills with Delta 4 program.",
    price: "₹299.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Apna College",
    image: img20,
  },
  {
    id: 21,
    title: "GDL Delta 5",
    description: "Final stage of Delta program for mastery.",
    price: "₹299.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Apna College",
    image: img21,
  },
  {
    id: 22,
    title: "GDL Dhruv ChatGpt",
    description: "Learn how to effectively use ChatGPT.",
    price: "₹249.00",
    originalPrice: "₹6,999.00",
    discount: "-98%",
    person: "Dhruv",
    image: img22,
  },
  {
    id: 23,
    title: "GDL Dhruv Time Management",
    description: "Master time management skills with Dhruv.",
    price: "₹249.00",
    originalPrice: "₹6,999.00",
    discount: "-98%",
    person: "Dhruv",
    image: img23,
  },
  {
    id: 24,
    title: "GDL Dhruv YT Without Watermark",
    description: "Learn to create YouTube videos without watermarks.",
    price: "₹249.00",
    originalPrice: "₹6,999.00",
    discount: "-98%",
    person: "Dhruv",
    image: img24,
  },
  {
    id: 25,
    title: "GDL Dot Batch By Love Babbar",
    description:
      "Join the Dot Batch for comprehensive learning with Love Babbar.",
    price: "₹299.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Love Babbar",
    image: img25,
  },
  {
    id: 26,
    title: "GDL Finance with Sharan",
    description: "Learn finance concepts and strategies with Sharan.",
    price: "₹299.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Sharan",
    image: img26,
  },
  {
    id: 27,
    title: "GDL Gigl Video Editing",
    description: "Master video editing skills with Gigl.",
    price: "₹299.00",
    originalPrice: "₹1,999.00",
    discount: "-90%",
    person: "Gigl",
    image: img27,
  },
  {
    id: 28,
    title: "GDL How To Instagram By Ankur Warikoo",
    description: "Learn effective Instagram strategies with Ankur Warikoo.",
    price: "₹299.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Ankur Warikoo",
    image: img28,
  },
  {
    id: 29,
    title: "GDL Mera Placement Hoga",
    description: "Prepare for placements with this comprehensive course.",
    price: "₹299.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Unknown",
    image: img29,
  },
  {
    id: 30,
    title: "GDL Namaste Frontend System Design",
    description: "Learn frontend system design with Namastedev.",
    price: "₹299.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Namastedev (Akshay Saini)",
    image: img30,
  },
  {
    id: 31,
    title: "GDL Namaste Node JS S02",
    description: "Learn Node.js in the second season with Namastedev.",
    price: "₹99.00",
    originalPrice: "₹6,969.00",
    discount: "-99%",
    person: "Namastedev (Akshay Saini)",
    image: img31,
  },
  {
    id: 32,
    title: "GDL Namaste Node JS S1 & S2 Both",
    description: "Get both seasons of Node.js together.",
    price: "₹199.00",
    originalPrice: "₹6,969.00",
    discount: "-96%",
    person: "Namastedev (Akshay Saini)",
    image: img32,
  },
  {
    id: 33,
    title: "GDL Namaste React From Zero to Hero",
    description: "Become a React expert from scratch with Namastedev.",
    price: "₹299.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Namastedev (Akshay Saini)",
    image: img33,
  },
  {
    id: 34,
    title: "GDL PW Decode DSA with C++ 1.0 & 2.0",
    description: "Deep dive into DSA with C++ in this comprehensive course.",
    price: "₹299.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "PW",
    image: img34,
  },
  {
    id: 35,
    title: "GDL Sanket Singh – Frontend Development in ReactJs",
    description: "Learn frontend development using React.js with Sanket Singh.",
    price: "₹299.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Sanket Singh",
    image: img35,
  },
  {
    id: 36,
    title: "GDL Sanket Singh – Learn Backend In NodeJS From Scratch",
    description: "Start your backend journey with Node.js from scratch.",
    price: "₹299.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Sanket Singh",
    image: img36,
  },
  {
    id: 37,
    title: "GDL Sanket Singh Advanced Backend Development In NODE (Lambda 3)",
    description: "Enhance your backend skills with advanced Node.js concepts.",
    price: "₹299.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Sanket Singh",
    image: img37,
  },
  {
    id: 38,
    title: "GDL Sanket Singh Backend in SpringBoot",
    description: "Learn backend development using SpringBoot.",
    price: "₹299.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Sanket Singh",
    image: img38,
  },
  {
    id: 39,
    title: "GDL Sanket Singh MERN Stack 2024",
    description: "Become proficient in the MERN stack for 2024.",
    price: "₹299.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Sanket Singh",
    image: img39,
  },
  {
    id: 40,
    title: "GDL Sheryians Frontend Domination",
    description: "Master frontend development with Sheryians.",
    price: "₹299.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Sheryians",
    image: img40,
  },
  {
    id: 41,
    title: "GDL SOIC",
    description: "Learn the fundamentals of SOIC.",
    price: "₹599.00",
    originalPrice: "₹6,969.00",
    discount: "-93%",
    person: "Unknown",
    image: img41,
  },
  {
    id: 42,
    title: "GDL Three JS",
    description: "Explore 3D graphics with Three.js.",
    price: "₹599.00",
    originalPrice: "₹6,969.00",
    discount: "-93%",
    person: "Unknown",
    image: img42,
  },
  {
    id: 43,
    title: "Iman Gadzhi’s Agency Accelerator 2024",
    description: "Accelerate your agency's growth with Iman Gadzhi.",
    price: "₹899.00",
    originalPrice: "₹6,969.00",
    discount: "-89%",
    person: "Iman Gadzhi",
    image: img43,
  },
  {
    id: 44,
    title:
      "Koray Tugberk Gubur – Topical Authority Semantic SEO (Fundamentals)",
    description:
      "Learn the fundamentals of topical authority and semantic SEO.",
    price: "₹899.00",
    originalPrice: "₹6,969.00",
    discount: "-89%",
    person: "Koray Tugberk Gubur",
    image: img44,
  },
  {
    id: 45,
    title: "Sanket Singh Master Complete Java + DSA + Backend + System Design",
    description:
      "Comprehensive course covering Java, DSA, backend, and system design.",
    price: "₹299.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Sanket Singh",
    image: img45,
  },
  {
    id: 46,
    title: "Sigma 4.0 By Apna College",
    description: "Join the Sigma 4.0 course for advanced learning.",
    price: "₹399.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Apna College",
    image: img46,
  },
  {
    id: 47,
    title: "Sigma 5.0 By Apna College",
    description: "Explore the latest in Sigma 5.0.",
    price: "₹599.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Apna College",
    image: img47,
  },
  {
    id: 48,
    title: "Simga 3.0",
    description: "Learn with the Simga 3.0 course.",
    price: "₹299.00",
    originalPrice: "₹6,969.00",
    discount: "-97%",
    person: "Apna College",
    image: img48,
  },
];
